### ISSUE TITLE
[feature-request] Add ability to use same telegraf plugin more than once

### ISSUE THREAD

**Issue by mlieberman85** [influxdata/tick-charts#11]
I know telegraf toml config allows you to use multiple instances of the same plugin in a single config (e.g. multiple cloudwatch plugins) however since values.yaml is yaml, yaml doesn't allow two of the same key. Is there a way in the chart to allow this?

**Comment by jackzampolin** [comment]
@mlieberman85 It would need to be refactored to make all the keys under `.Values.config.{{ outputs,inputs }}` an array instead.

**Comment by amoskyler** [comment]
@mlieberman85 @jackzampolin I've created a pull request which accomplishes this against the kubernetes/charts repo.

A maintainer closed it however as the one in kubernetes/charts is deprecated. I can look at porting it to this repository. Or of course...it can be updated in the other one. It would be nice to get a link between the kubernetes/charts repo and this one.

https://github.com/kubernetes/charts/pull/4170

**Comment by jackzampolin** [comment]
Thanks @amoskyler! I don't have access on this repo anymore so I would cc @timhallinflux on this. This would be a _great_ feature.

**Comment by maddisondavid** [comment]
+1 for this.  We have a configuration with multiple InfluxDB outputs depending on the different tags.  Currently I'm unable to express this in a way that the current chart will accept  (since we need multiple `[[outputs.influxdb]]` sections.

At the very least the chart could have something like an `extraConfig` section that allows the user to express an extra config block that is just appended to the end of the generated `telegraf.conf`

**Comment by maddisondavid** [comment]
@amoskyler do you have any plans to port your PR over to this repo?  I think it represents a big missing feature and it would be a shame for your work to get lost.

**Comment by amoskyler** [comment]
Hey @maddisondavid I was just thinking about this yesterday. I definitely want to get this added. I will port it over here and submit a PR in the next day or two.

**Comment by amoskyler** [comment]
@maddisondavid I've created a PR here https://github.com/influxdata/tick-charts/pull/28

@timhallinflux Would you be up to take a look and give feedback?

**Comment by amoskyler** [comment]
@timhallinflux additionally, has there been any consideration of merging this chart downstream to the kubernetes/charts repository? I know the charts over there were deprecated, but I don't understand the reasoning.
