### ISSUE TITLE
Repo Revival

### ISSUE THREAD

**Issue by naseemkullah** [influxdata/tick-charts#115]
Stable and Incubator charts are going to be extinct in a year. Would be nice to revive this repo if influxdata has the bandwith to.
https://github.com/helm/charts#deprecation-timeline

**Comment by russorat** [comment]
@naseemkullah thanks for this! yes, this repo needs some love. let me see what i can do internally to get some of these prs reviewed.

**Comment by naseemkullah** [comment]
Hi @russorat I was thinking this would be a good opportunity to re write some of these charts entirely with the new v2 charts api (compatible only with helm3)... we can post on the stable repo that as folks transition to helm3 they can use the shiny new charts hereby hosted

**Comment by naseemkullah** [comment]
there has been a lot of added features to the influxdb chart in stable repo for example that we can port over during this transition, I would gladly help for the influxdb chart as we do use it at my org, I have already signed the influx CLA

**Comment by rawkode** [comment]
@naseemkullah I've already written a Helm 3 compatible chart for InfluxDB 2

I'll get the v1 charts updated too. If you wish to pair on this, I'd be happy to work with you.

**Comment by naseemkullah** [comment]
Sounds great @rawkode, is that new chart in this repo?

**Comment by rawkode** [comment]
https://github.com/rawkode/influxdb-examples/tree/master/influxdbv2-helm-chart

**Comment by naseemkullah** [comment]
Looks good, maybe take the opportunity to use recommended labels (matter of preference though) (https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels)  and  add serviceAccount as per https://helm.sh/docs/topics/chart_best_practices/rbac/ ... also `stable/influxdb` has nice features such a backup cronjob to backup and upload to GCS or Azure Object Store, someone is bound to add for S3 and other storage backends I'm sure.

https://github.com/helm/charts/blob/master/stable/influxdb/templates/backup-cronjob.yaml

**Comment by Aisuko** [comment]
@naseemkullah   cc @scottrigby  I'm sorry to reply so late. I'm happy to as a maintainer of stable/influxdb. I think there may an example of how to move the stable/chart https://github.com/jaegertracing/jaeger/issues/1976 .  I agree with the content of this issue. The most important for the end-user is to avoid any broken changes and easy to search in Helm Hub to use.  So, In my opinion, we should follow that.

**Comment by mgcrea** [comment]
Any update on the new charts? Wouldn't it be better to have them hosted as a repo: (eg. like cert-manager: `helm repo add jetstack https://charts.jetstack.io`).

I'm now encountering issues with `stable/chronograf`:
`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"`, so it might looks like we have no longer working options to deploy a tick stack using helm.

**Comment by naseemkullah** [comment]
> Any update on the new charts? Wouldn't it be better to have them hosted as a repo: (eg. like cert-manager: `helm repo add jetstack https://charts.jetstack.io`).
> 

That would indeed be the plan!

> I'm now encountering issues with `stable/chronograf`:
> `Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"`, so it might looks like we have no longer working options to deploy a tick stack using helm.

I'd suggest opening a PR to the stable repo to update the api version of the Deployment object! That chart definitely needs some TLC.

**Comment by rawkode** [comment]
Hi all,

We know that this is currently very frustrating, but please know that we're actively working on this.

I'm currently traveling to an event, but I'll get the automation in place for the new charts completed in the next 48 hours and get the stable charts moved over and updated.

Thank you for your patience

**Comment by naseemkullah** [comment]
Np @rawkode ! Enjoy the event.

If you'd like help (in particular if wanting to use https://github.com/helm/chart-releaserand github actions for CI, which work amazingly) I'm sure @scottrigby form Helm would be willing to help with the move!

**Comment by rawkode** [comment]
We've not migrated the stable charts to https://github.com/influxdata/helm-charts

We'll add the repo to the Helm Hub when we've finalised the DNS name we wish to use.

Closing this for now, please open new issues on the new repo :D

**Comment by naseemkullah** [comment]
Yay!
