### ISSUE TITLE
Use Okta as oauth provider

### ISSUE THREAD

**Issue by ajayanaj** [influxdata/tick-charts#118]
Hello,

I would like to use "Okta" as oauth provider, but I couldn't see any option in the chart to use "Okta", I see only Google, heroku and heroku. 

I tried to put my Okta configs under oauth, but it didn't worked. 
Could you please help me to use "Okta" ?

**Comment by russorat** [comment]
This repo has been deprecated. Please see the updated helm charts at https://github.com/influxdata/helm-charts
