### ISSUE TITLE
InfluxDB chart failed to install due to missing Admin section

### ISSUE THREAD

**Issue by maddisondavid** [influxdata/tick-charts#32]
The 1.6.1 InfluxDB chart fails to install as the `admin` section was removed from the default values.  Attempting to install give the following:

```
$> helm install --name data --namespace tick influx/influxdb
Error: render error in "influxdb/templates/service.yaml": template: influxdb/templates/service.yaml:18:16: executing "influxdb/templates/service.yaml" at <.Values.config.admin...>: can't evaluate field enabled in type interface {}
```

### Resolution

Adding the following to my values allowed the chart to install:

```
config:
   admin:
      enabled: false
      https_enabled: false
```

**Comment by jackzampolin** [comment]
I think theres an open pull to fix this issue: https://github.com/influxdata/tick-charts/pull/31

**Comment by jackzampolin** [comment]
cc @timhallinflux

**Comment by timhallinflux** [comment]
the [admin] section of the config has been deprecated.  Looks like I didn't pull it from the various templates which were looking for it.  This should be resolved.
