### ISSUE TITLE
Add tick-charts to https://hub.kubeapps.com/

### ISSUE THREAD

**Issue by sudermanjr** [influxdata/tick-charts#70]
Just a suggestion that it would be cool to see this repo in https://hub.kubeapps.com/.  Just found these by random chance and they work really well.

**Comment by jackzampolin** [comment]
@sudermanjr Thank you 😊! The versions from the official helm repo are on there, but these are not. It would be a good add!

**Comment by sudermanjr** [comment]
Just realized I had the wrong link.  I think this might be better. https://hub.helm.sh/
